- name: Show NTP
  hosts: devices
  gather_facts: no
  become: yes
  become_method: enable

  tasks:
    - name: Check NTP status
      ios_command:
        commands:
          - show ntp associations
      register: ntp_status

    - name: Display NTP sync status
      debug:
        var: ntp_status.stdout_lines

#TASK [Display NTP sync status] *************************************************
#ok: [R1-T] => {
#    "ntp_status.stdout_lines": [
#        [
#            "address         ref clock       st   when   poll reach  delay  offset   disp",
#            "*~192.168.2.2     127.127.1.1      8    116     64     1  1.852 -1816.5 7937.9",
#            " * sys.peer, # selected, + candidate, - outlyer, x falseticker, ~ configured"
#        ]
#    ]
#}
#ok: [R2] => {
#    "ntp_status.stdout_lines": [
#        [
#            "address         ref clock       st   when   poll reach  delay  offset   disp",
#            "*~192.168.2.2     127.127.1.1      8    116     64     1  1.852 -1816.8 7937.9",
#            " * sys.peer, # selected, + candidate, - outlyer, x falseticker, ~ configured"
#        ]
#    ]
#}
#ok: [R3] => {
#    "ntp_status.stdout_lines": [
#        [
#            "address         ref clock       st   when   poll reach  delay  offset   disp",
#            "*~192.168.2.2     127.127.1.1      8     14     64    37  3.850  -4.731  3.664",
#            " * sys.peer, # selected, + candidate, - outlyer, x falseticker, ~ configured"
#        ]
#    ]
#}
#ok: [LAN1] => {
#    "ntp_status.stdout_lines": [
#        [
#            "address         ref clock       st   when   poll reach  delay  offset   disp",
#            "*~192.168.2.2     127.127.1.1      8    116     64     1  2.852 -1816.6 7937.9",
#            " * sys.peer, # selected, + candidate, - outlyer, x falseticker, ~ configured"
#        ]
#    ]
#}
#ok: [LAN2] => {
#    "ntp_status.stdout_lines": [
#        [
#            "address         ref clock       st   when   poll reach  delay  offset   disp",
#            "*~192.168.2.2     127.127.1.1      8    116     64     1  0.911 -1817.0 7937.9",
#            " * sys.peer, # selected, + candidate, - outlyer, x falseticker, ~ configured"
#        ]
#    ]
#}
