- name: "VLAN Playbook"
  hosts: switches
  gather_facts: no
  become: yes
  become_method: enable

  vars: 
    vlan_list:
      - vlan_id: 10
        name: VLAN10
      - vlan_id: 20
        name: VLAN20
      - vlan_id: 30
        name: VLAN30

  tasks:
    - name: "Create VLANs"
      ios_config:
        lines:
          - "vlan {{ item.vlan_id }}"
          - "name {{ item.name }}"
        parents: "vlan {{ item.vlan_id }}"
        match: exact
      loop: "{{ vlan_list }}"
      

    - name: "Shutdown VLAN interfaces if they exist"
      ios_config:
        lines:
          - shutdown
        parents: "interface vlan {{ item.vlan_id }}"
        match: line
        replace: line  
      loop: "{{ vlan_list }}"
    
    - name: "Save configuration"
      ios_config:
        save_when: modified 


#TASK [Create VLANs] ************************************************************
#changed: [LAN2] => (item={'vlan_id': 10, 'name': 'VLAN10'})
#changed: [LAN1] => (item={'vlan_id': 10, 'name': 'VLAN10'})
#changed: [LAN2] => (item={'vlan_id': 20, 'name': 'VLAN20'})
#changed: [LAN2] => (item={'vlan_id': 30, 'name': 'VLAN30'})
#changed: [LAN1] => (item={'vlan_id': 20, 'name': 'VLAN20'})
#changed: [LAN1] => (item={'vlan_id': 30, 'name': 'VLAN30'})
#
#TASK [Shutdown VLAN interfaces if they exist] **********************************
#changed: [LAN2] => (item={'vlan_id': 10, 'name': 'VLAN10'})
#changed: [LAN1] => (item={'vlan_id': 10, 'name': 'VLAN10'})
#changed: [LAN2] => (item={'vlan_id': 20, 'name': 'VLAN20'})
#changed: [LAN1] => (item={'vlan_id': 20, 'name': 'VLAN20'})
#changed: [LAN2] => (item={'vlan_id': 30, 'name': 'VLAN30'})
#changed: [LAN1] => (item={'vlan_id': 30, 'name': 'VLAN30'})
#
#TASK [Save configuration] ******************************************************
#changed: [LAN2]
#changed: [LAN1]

